"""Create drunkards table

Revision ID: 65b976d2208f
Revises: 
Create Date: 2026-07-04 11:06:17.770699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b976d2208f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drunkard',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shots_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('drunk_time', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('unmute_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drunkard')
    # ### end Alembic commands ###
