"""Add removed roles id column

Revision ID: 74fe61846b28
Revises: b82ef91d4b5d
Create Date: 2026-07-19 20:46:03.128305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74fe61846b28'
down_revision: Union[str, Sequence[str], None] = 'b82ef91d4b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drunkard', sa.Column('removed_role_ids', postgresql.ARRAY(sa.BigInteger()), server_default=sa.text('ARRAY[]::bigint[]'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drunkard', 'removed_role_ids')
    # ### end Alembic commands ###
