"""Rename unmute_date to sobriety date

Revision ID: b82ef91d4b5d
Revises: 65b976d2208f
Create Date: 2026-07-04 12:22:26.166580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b82ef91d4b5d'
down_revision: Union[str, Sequence[str], None] = '65b976d2208f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drunkard', sa.Column('sobriety_date', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'drunkard', ['id'])
    op.drop_column('drunkard', 'unmute_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drunkard', sa.Column('unmute_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drunkard', type_='unique')
    op.drop_column('drunkard', 'sobriety_date')
    # ### end Alembic commands ###
